# Generated by Django 5.0.2 on 2025-05-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emdcbackend', '0007_mapawardtocontest_judge_redesign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='championship',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teams',
            name='championship_score',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mapscoresheettoteamjudge',
            name='sheetType',
            field=models.IntegerField(choices=[(1, 'Presentation'), (2, 'Journal'), (3, 'Machinedesign'), (4, 'Runpenalties'), (5, 'Otherpenalties'), (6, 'Redesign'), (7, 'Championship')]),
        ),
        migrations.AlterField(
            model_name='scoresheet',
            name='sheetType',
            field=models.IntegerField(choices=[(1, 'Presentation'), (2, 'Journal'), (3, 'Machinedesign'), (4, 'Runpenalties'), (5, 'Otherpenalties'), (6, 'Redesign'), (7, 'Championship')]),
        ),
    ]
